[package]
name = "turbin3_q2_2025_solana_req"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-sdk = "1.15.2"
bs58 = "0.5.1"
solana-client = "1.15.2"
solana-program = "1.15.2"
borsh = "1.5.7"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git", branch = "master" }